### ISSUE TITLE
www.msmarco.org web site not found

### ISSUE THREAD

**Issue by ronsoohyeong** [microsoft/MSMARCO-Question-Answering#11]
Please check if this web site works. 
http://www.msmarco.org/dataset.aspx

It only shows this error:
~~~
404 Web Site not found.
You may be seeing this error due to one of the reasons listed below :

Custom domain has not been configured inside Azure. See how to map an existing domain to resolve this.
Client cache is still pointing the domain to old IP address. Clear the cache by running the command ipconfig/flushdns.
Checkout App Service Domain FAQ for more questions.
~~~

**Comment by sxwxs** [comment]
C:\Users\xxx>nslookup www.msmarco.org
服务器:  UnKnown
Address:  10.3.9.6

*** UnKnown 找不到 www.msmarco.org: Non-existent domain

**Comment by skyprince999** [comment]
Any update on this? Can the contributors comment on its availability.? @microsoftopensource 
@spacemanidol

**Comment by ronsoohyeong** [comment]
Now I can see the web page, but the Submit button in Terms and Conditions does not work. Can you please check?

**Comment by spacemanidol** [comment]
This is my bad. I was migrating things from a old webapp to github based pages. msmarco.org now redirects to the new github based domain. @ronsoohyeong I had a typo in the download function which I fixed. You should be able to download things now.
