### ISSUE TITLE
dataset files removed

### ISSUE THREAD

**Issue by seanmacavaney** [microsoft/MSMARCO-Question-Answering#16]
Hi all,

The MS MARCO files were recently moved from `msmarco.blob.core.windows.net` to `msmarco.z22.web.core.windows.net`. However, it looks like now the QnA data are no longer available anywhere. (At least, nowhere I can find...). I know the dataset is retired, but the data is still helpful/important for some experiments, reproducing existing results, etc.

Are there plans to continue hosting the QnA data somewhere?

Thanks,
sean

**Comment by seanmacavaney** [comment]
bump @bmitra-msft!

**Comment by bhaskar-mitra** [comment]
Hi @seanmacavaney, thanks for flagging this. Let me take a look and get back. Do you have one of the QnA data links that is currently broken? I will try to track down where the data is located and work on where it should be migrated.

**Comment by seanmacavaney** [comment]
Thanks! The files used to be located here:

  - https://msmarco.blob.core.windows.net/msmarco/train_v2.1.json.gz
  - https://msmarco.blob.core.windows.net/msmarco/dev_v2.1.json.gz
  - https://msmarco.blob.core.windows.net/msmarco/eval_v2.1_public.json.gz

**Comment by bhaskar-mitra** [comment]
This should be resolved now. Can you please double-check and close the issue if it's resolved. Thanks so much again for reporting this. I had missed moving a few of the folders during the migration earlier.

**Comment by seanmacavaney** [comment]
Worked like a charm and the hashes match! Thanks @bmitra-msft!
